-- Additive production schema for guided Telegram equipment intake.
create table if not exists public.telegram_equipment_reports (
  id bigint generated by default as identity primary key,
  warehouse text not null,
  category text not null,
  device_type text not null default '',
  module text,
  device_number text not null default '',
  description text not null default '',
  photo_url text,
  employee text not null default '',
  telegram_user_id bigint,
  telegram_username text not null default '',
  telegram_chat_id bigint,
  topic_id bigint,
  source_message_id bigint,
  answers jsonb not null default '{}'::jsonb,
  path jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (telegram_chat_id, source_message_id)
);
create index if not exists telegram_equipment_reports_created_at_idx on public.telegram_equipment_reports (created_at desc);
create index if not exists telegram_equipment_reports_device_idx on public.telegram_equipment_reports (category, device_number, warehouse);

create table if not exists public.telegram_devices_to_add (
  id bigint generated by default as identity primary key,
  category text not null,
  device_type text not null default '',
  device_number text not null,
  warehouse text not null,
  employee text not null default '',
  telegram_user_id bigint,
  report_description text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique (category, device_type, device_number, warehouse)
);
create index if not exists telegram_devices_to_add_status_idx on public.telegram_devices_to_add (status, created_at);

create table if not exists public.telegram_intake_options (
  id bigint generated by default as identity primary key,
  node_id text not null,
  option_id text not null,
  label text not null,
  next_node text,
  description text not null default '',
  icon text not null default '',
  only_for jsonb not null default '[]'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  unique (node_id, option_id)
);

alter table public.telegram_equipment_reports enable row level security;
alter table public.telegram_devices_to_add enable row level security;
alter table public.telegram_intake_options enable row level security;
-- Access is through the server's service-role key; no anon/authenticated policies are added.
