-- ============================================================
-- Редактор дерева приёма ошибок, версия 2 (полная настройка).
--
-- Что делает: превращает `telegram_intake_options` из таблицы «только
-- добавления» в полноценный слой переопределений поверх встроенного
-- дерева из `equipment_intake/tree_config.py`.
--
-- Было: строка = НОВЫЙ вариант, который дописывается к встроенным.
-- Стало: строка = вариант узла, который может быть
--          * добавленным (is_builtin = false, как раньше);
--          * правкой встроенного (is_builtin = true, тот же option_id) —
--            новая подпись/описание/иконка/цель;
--          * скрытым встроенным (is_builtin = true, hidden = true) —
--            вариант остаётся в коде, но сотрудник его не видит.
--
-- Плюс nodes: правки заголовка/описания/подсказки/цели узла и скрытие
-- целого узла. Создание и удаление узлов намеренно НЕ добавлено: в дереве
-- нет обратных ссылок, и удаление узла оставило бы висячие `next_node`
-- (см. отчёт). Скрытие узла — безопасная замена удалению.
--
-- Совместимость: старые строки (без новых колонок) читаются как раньше —
-- добавленные варианты. Новые колонки имеют значения по умолчанию, поэтому
-- старый код продолжает работать и после применения миграции.
--
-- Идемпотентность: можно применять повторно, `if not exists` везде.
-- Живая база НЕ затрагивается этим файлом — применяет владелец вручную.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Новые колонки в telegram_intake_options
-- ------------------------------------------------------------
-- is_builtin — строка переопределяет ВСТРОЕННЫЙ вариант с тем же
--              option_id, а не добавляет новый. По умолчанию false:
--              все существующие строки остаются добавленными.
alter table public.telegram_intake_options
  add column if not exists is_builtin boolean not null default false;

-- hidden — вариант не показывать сотруднику (и встроенный, и добавленный).
--          Скрывать, а не удалять: удаление встроенного варианта нельзя
--          сохранить одной строкой, а «показать обратно» — одна правка.
alter table public.telegram_intake_options
  add column if not exists hidden boolean not null default false;

-- sort_order — порядок варианта внутри узла. Меньше — выше. Встроенные
--              варианты из кода получают позицию по своему индексу, поэтому
--              значения по умолчанию (0) не ломают прежний вид.
alter table public.telegram_intake_options
  add column if not exists sort_order integer not null default 0;

-- Обновляем существующие строки, чтобы порядок был осмысленным: сначала
-- по узлу, затем по времени создания. Повторный запуск ничего не портит.
with ordered as (
  select id,
         row_number() over (
           partition by node_id order by created_at asc, id asc
         ) - 1 as position
    from public.telegram_intake_options
   where is_builtin = false
)
update public.telegram_intake_options as target
   set sort_order = ordered.position
  from ordered
 where target.id = ordered.id
   and target.is_builtin = false;

-- Индекс под основной запрос редактора: «все строки одного узла».
create index if not exists telegram_intake_options_node_idx
  on public.telegram_intake_options (node_id, sort_order, id);

-- Метаданные правки — видно, кто и когда менял вариант.
alter table public.telegram_intake_options
  add column if not exists updated_by text;

alter table public.telegram_intake_options
  add column if not exists updated_at timestamptz;


-- ------------------------------------------------------------
-- 2. Таблица правок узлов
-- ------------------------------------------------------------
-- Узел описывается кодом (id, тип, key, next_node). Здесь лежат только
-- ПЕРЕОПРЕДЕЛЕНИЯ: title, description, placeholder, stub_hint, next_node,
-- hidden. Строка появляется при первой правке узла.
create table if not exists public.telegram_intake_nodes (
  id bigint generated by default as identity primary key,
  node_id text not null unique,
  title text,                 -- null = не переопределено, берём из кода
  description text,
  placeholder text,
  stub_hint text,
  next_node text,             -- переопределение перехода узла (INPUT/NUMBER)
  hidden boolean not null default false,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists telegram_intake_nodes_node_idx
  on public.telegram_intake_nodes (node_id);

alter table public.telegram_intake_nodes enable row level security;
-- Доступ только через service-role ключ сервера (как у остальных таблиц
-- бота). Политик для anon/authenticated намеренно нет.

alter table public.telegram_intake_options enable row level security;


-- ============================================================
-- ОТКАТ (выполнять только если нужно вернуть прежнее поведение):
--
--   drop table if exists public.telegram_intake_nodes;
--
--   drop index if exists public.telegram_intake_options_node_idx;
--   alter table public.telegram_intake_options drop column if exists updated_at;
--   alter table public.telegram_intake_options drop column if exists updated_by;
--   alter table public.telegram_intake_options drop column if exists sort_order;
--   alter table public.telegram_intake_options drop column if exists hidden;
--   alter table public.telegram_intake_options drop column if exists is_builtin;
--
-- Внимание: откат колонок стирает правки встроенных вариантов и порядок.
-- Перед откатом сохраните таблицу: create table ..._backup as select * from ...
-- ============================================================
